version: "3"

services:
  nodeosd:
    image: eosio/eos:20180526
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  branch: $GITHUB_BRANCH

    command: /opt/eosio/bin/nodeosd.sh --max-transaction-time=1000
    ports:
      - 8888:8888
      - 9876:9876

  nginx:
    image: xqdocker/ubuntu-nginx
    ports:
      - 888:80
    volumes:
      - ./default-node:/etc/nginx/conf.d/default.conf
    links:
      - nodeosd

  keosd:
    image: eosio/eos:20180526
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir
    hostname: keosd
    links:
      - nodeosd
